# Generated by Django 5.2.7 on 2025-10-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_manager_app', '0003_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('In_progress', 'In progress'), ('Resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
