# Generated by Django 5.2.7 on 2025-10-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_manager_app', '0005_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
